#spring.rabbitmq.host=118.24.44.169
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
##spring.rabbitmq.virtual-host=

spring:
  rabbitmq:
    host: 116.62.48.220
    username: admin
    password: admin
    virtual-host: /java_mmr # 斜杠必须写上，该虚拟主机需要手动创建，在rabbit管理界面admin->virtual-host
    port: 5672